import os

TELEGRAM_BOT_TOKEN = os.environ["TELEGRAM_BOT_TOKEN"]
OPENAI_API_KEY = os.environ["OPENAI_API_KEY"]
ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")
OURA_ACCESS_TOKEN = os.environ.get("OURA_ACCESS_TOKEN", "")

DATABASE_URL = os.environ.get("DATABASE_URL", "")

TIMEZONE = "Europe/Moscow"
MORNING_BRIEFING_HOUR = 7
MORNING_BRIEFING_MINUTE = 0
EVENING_DIGEST_HOUR = 22
EVENING_DIGEST_MINUTE = 0

READINESS_LOW_THRESHOLD = 65
READINESS_CRITICAL_THRESHOLD = 50
FATIGUE_PATTERN_DAYS = 3
REMINDER_PING_MINUTES = 5
MAX_PINGS = 2

GPT_MODEL = "gpt-4o"
GPT_TEMPERATURE = 0.3
GPT_MAX_TOKENS = 2000
WHISPER_MODEL = "whisper-1"

OURA_BASE_URL = "https://api.ouraring.com/v2"
